import type { ExperienceItem } from "@/types";

export const EXPERIENCES: ExperienceItem[] = [
  {
    company: "Knorex India Pvt Ltd",
    role: "Software Engineer I",
    location: "Pune, India",
    startDate: "2022-04",
    endDate: null,
    achievements: [
      "Architected micro frontend system using component isolation and domain-driven modules, reducing code duplication by 50%.",
      "Reduced API overhead by 60% by implementing server-side search with debouncing and a hybrid pagination strategy.",
      "Engineered a multi-level RBAC system with secure data isolation across 1000+ enterprise accounts.",
      "Delivered an ad integration platform supporting Google, Meta, LinkedIn and TikTok Ads APIs.",
      "Built a reusable component library and custom React hooks using functional components and modern hook patterns.",
      "Optimized rendering performance with React.memo, useMemo and useCallback — improving UI responsiveness for data-heavy dashboards.",
      "Scaled a Zustand state architecture to support 1000+ concurrent enterprise user sessions.",
      "Contributed to CI/CD pipelines using GitHub Actions, streamlining build and deployment workflows.",
      "Converted Figma / UX designs into responsive, pixel-perfect user interfaces.",
    ],
    stack: [
      "React",
      "Next.js",
      "TypeScript",
      "Zustand",
      "Micro Frontend",
      "Tailwind CSS",
      "GitHub Actions",
      "Figma",
    ],
  },
  {
    company: "V2STech Solutions Pvt Ltd",
    role: "Software Developer",
    location: "Mumbai, India",
    startDate: "2020-06",
    endDate: "2022-04",
    achievements: [
      "Built an enterprise dashboard for Identity and Access Management (IAM) with role-based permission flows.",
      "Designed dynamic interfaces for user roles, permissions and audit logs used by 500+ admin users.",
      "Integrated RESTful APIs for real-time data visualization and operational reporting.",
      "Implemented advanced filtering, search and pagination — reducing data retrieval time by ~40%.",
      "Enhanced UI performance across complex enterprise workflows through component memoization and lazy loading.",
    ],
    stack: [
      "React",
      "JavaScript",
      "Redux",
      "REST APIs",
      "Material UI",
    ],
  },
  {
    company: "SpryOX Pvt Ltd",
    role: "UI/UX Developer",
    location: "Mumbai, India",
    startDate: "2019-01",
    endDate: "2020-05",
    achievements: [
      "Converted Figma / PSD designs into pixel-perfect, responsive UIs using HTML5, CSS3, SCSS and React.",
      "Delivered cross-browser compatible applications (Chrome, Firefox, Safari, Edge) with consistent UX.",
      "Boosted page load performance by 30% through CSS optimization, asset minification and image compression.",
      "Built interactive UI features using JavaScript (ES6+), jQuery and modular component patterns.",
    ],
    stack: [
      "React",
      "JavaScript",
      "HTML5",
      "CSS3",
      "SCSS",
      "jQuery",
    ],
  },
  {
    company: "Kush Infosystems Pvt Ltd",
    role: "Web Developer",
    location: "Mumbai, India",
    startDate: "2017-10",
    endDate: "2019-01",
    achievements: [
      "Designed responsive web pages using HTML5, CSS3 and Bootstrap — delivering 100+ client projects.",
      "Customized WordPress themes and plugins for business websites.",
      "Converted PSD / Figma design assets into functional, cross-browser web pages.",
    ],
    stack: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "WordPress",
      "jQuery",
    ],
  },
];
