import type { Project } from "@/types";

export const PROJECTS: Project[] = [
  {
    slug: "pathlock",
    title: "Pathlock",
    tagline: "Enterprise Identity Governance Platform",
    description:
      "A unified identity governance and risk platform used by 1,300+ enterprise accounts. Built a reusable React component library and multi-level RBAC system powering Access Risk Analysis, User Access Reviews and Privileged Access Management.",
    features: [
      "Architected a reusable React component library (DataTable, RBACBadge, AuditLog, RoleMatrix) used across Access Risk Analysis, User Access Reviews and Privileged Access Management — reducing cross-team code duplication by 50%.",
      "Designed and implemented a multi-level RBAC permission system controlling UI visibility at feature, field and action levels across 1,300+ enterprise accounts.",
      "Optimized performance by reducing API overhead by 60% using server-side search, debouncing, React Query caching and hybrid pagination.",
      "Built scalable UI for SoD risk dashboards and audit logs, handling large datasets with smooth UX.",
      "Implemented unit and integration testing using Jest + React Testing Library, improving component reliability and reducing production bugs.",
      "Performed end-to-end testing with Cypress for critical access control workflows.",
      "Collaborated with backend teams to standardize API contracts and improve response efficiency.",
    ],
    stack: [
      "React.js",
      "TypeScript",
      "Storybook",
      "Zustand",
      "Ant Design",
      "Node.js",
      "REST APIs",
      "Jest",
      "React Testing Library",
      "Cypress",
    ],
    image: "/projects/pathlock.svg",
    liveUrl: "https://pathlock.com",
    accent: "from-violet-500 to-fuchsia-500",
  },
  {
    slug: "cantabnyc",
    title: "CantabNYC",
    tagline: "Alumni Event Management Platform",
    description:
      "A modern alumni events platform featuring multi-step ticketing, real-time RSVPs over WebSocket, and dynamic event archives. Designed for smooth UX across large datasets and complex validation flows.",
    features: [
      "Engineered a multi-step event registration and ticketing system using React Hook Form + Zod validation — supporting ticket tiers, pricing rules, dietary preferences and deadlines.",
      "Built a real-time RSVP system with WebSocket integration for live attendee count and sold-out state management.",
      "Developed a dynamic event archive with date-based filtering and optimized rendering for large datasets.",
      "Wrote unit tests for forms and UI components using Jest + React Testing Library to ensure validation accuracy.",
      "Conducted API testing and validation workflows using Postman.",
    ],
    stack: [
      "TypeScript",
      "Zustand",
      "Recharts",
      "WebSocket",
      "React Hook Form",
      "Zod",
      "Material UI",
      "Jest",
      "React Testing Library",
    ],
    image: "/projects/cantabnyc.svg",
    liveUrl: "https://www.cantabnyc.org",
    accent: "from-sky-500 to-cyan-400",
  },
  {
    slug: "task-manager",
    title: "Task Manager",
    tagline: "Full-stack MERN productivity app",
    description:
      "A full-stack MERN task manager with JWT-based authentication, protected routes, RESTful APIs and a scalable folder architecture — backed by Jest + Supertest tests and continuous deployment.",
    features: [
      "Engineered a full-stack MERN application with JWT-based authentication, protected routes and session management.",
      "Designed and developed RESTful APIs for task lifecycle management (CRUD, filtering, search, status tracking).",
      "Implemented debounced API requests to improve performance and reduce server load.",
      "Wrote backend API tests using Supertest and unit tests using Jest to ensure endpoint reliability.",
      "Structured scalable folder architecture and reusable components for maintainability.",
      "Deployed application using Vercel (frontend) and cloud backend services.",
    ],
    stack: [
      "MongoDB",
      "Express.js",
      "React.js",
      "Node.js",
      "SASS",
      "JWT",
      "Axios",
      "Jest",
      "Supertest",
      "Vercel",
      "CI/CD",
    ],
    image: "/projects/task-manager.svg",
    liveUrl: "https://tasks-app-frontend-omega.vercel.app",
    accent: "from-emerald-500 to-teal-400",
  },
];
